server:
  port: 8888
  servlet:
    context-path: /druid
spring:
  profiles:
    active: dev
  datasource:
    druid:
      filter:
        wall:
          enabled: true
          config:
            update-where-none-check: true
            delete-where-none-check: true
          log-violation: true
          throw-exception: true
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml